# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 10

    - name: Install
      run: yarn install
    
    - name: Test
      run: yarn test
    
    - name: Build
      run: yarn build:prod
    
    - name: Deploy
      run: |
        echo "Setting up SSH key..."
        echo "Creating ~/.ssh/"
        mkdir -p ~/.ssh
        
        echo "Writing SSH into ~/.ssh/..."
        echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/do_ssh
        
        echo "Setting chmod 0600 perms..."
        chmod 0600 ~/.ssh/do_ssh
        
        echo "Setting up known_hosts..."
        ssh-keyscan -H ${{secrets.HOST}} > ~/.ssh/known_hosts
        
        echo "Clear out remote dist dir..."
        ssh -i ~/.ssh/do_ssh edward@${{ secrets.HOST }} rm -rf /var/www/edwarddamato.com/dist/
        
        scp -i ~/.ssh/do_ssh -r dist edward@${{ secrets.HOST }}:/var/www/edwarddamato.com/
        
        echo "Clear out remote html dir..."
        ssh -i ~/.ssh/do_ssh edward@${{ secrets.HOST }} rm -rf /var/www/edwarddamato.com/html/
        
        echo "Rename remote dist to html..."
        ssh -i ~/.ssh/do_ssh edward@${{ secrets.HOST }} mv /var/www/edwarddamato.com/dist/ /var/www/edwarddamato.com/html/
        
        echo "Clean out SSH key..."
        rm ~/.ssh/do_ssh
        
        echo "Done!"
        
